server:
  port: 8127
  servlet:
    context-path: /api
spring:
  application:
    name: ai-code-screenshot
  profiles:
    active: local
screenshot:
  pool-size: 5
  browser-width: 1600
  browser-height: 900
# Dubbo
dubbo:
  application:
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
